services:
  # Base de Datos PostgreSQL
  # Puerto Interno: 5432 (Est√°ndar)
  # Puerto Externo: 5433 (Para evitar conflicto con tu PC)
  db:
    image: postgres:15-alpine
    container_name: adtdcbba_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=adtdcbba_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - adtdcbba_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis (Cache y WebSockets)
  # Puerto Externo: 6380
  redis:
    image: redis:7-alpine
    container_name: adtdcbba_redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - adtdcbba_net

networks:
  adtdcbba_net:
    driver: bridge

volumes:
  postgres_data: